plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.telegram:telegrambots-longpolling:7.10.0'

    implementation 'org.telegram:telegrambots-client:7.10.0'

    implementation 'org.slf4j:slf4j-simple:2.0.13'
}

application {
    mainClass = 'com.flowme.BotApplication'
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}